### ISSUE TITLE
for loop

### ISSUE THREAD

**Issue by jzych** [tomasz0/Kurs-2#2]
to nie powino byc w nawiasach klamrowych {} ? What that loop even do?
https://github.com/tomasz0/Kurs-2/blob/4e09f91936e8b434a7b4aa0060f6ab9d68286003/exc12.cpp#L26-L28

**Comment by tomasz0** [comment]
ta pętla zapełnia wektor V losowanymi wartościami 

vector<int>v2  nie należy do pętli to po prostu definicja nowego wektora gdzie będę umieszczał liczby pierwsze

**Comment by jzych** [comment]
popraw wiec formatowanie

**Comment by tomasz0** [comment]
poprawiłem co nie co
